# Generated by Django 3.0.8 on 2020-08-10 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
        migrations.RenameField(
            model_name='image',
            old_name='images',
            new_name='hotel',
        ),
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
