# Generated by Django 3.0.8 on 2020-08-11 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_analysis', '0005_auto_20200811_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='image_analysis.Hotel'),
        ),
    ]
